default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials[:development][:username] %>
  password: <%= Rails.application.credentials[:development][:password] %>
  host: localhost
  database: app_development

test:
  <<: *default
  username: <%= Rails.application.credentials[:development][:username] %>
  password: <%= Rails.application.credentials[:development][:password] %>
  host: localhost
  database: app_test

production:
  <<: *default
  username: <%= Rails.application.credentials[:production][:username] %>
  password: <%= Rails.application.credentials[:production][:password] %>
  host: <%= Rails.application.credentials[:production][:host] %>
  database: <%= Rails.application.credentials[:production][:database] %>
  port: <%= Rails.application.credentials[:production][:port] %>